//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mabato_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsRecord
    {
        public int Id { get; set; }
        public string LRN { get; set; }
        public string LRN_No { get; set; }
        public string Returning { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string MI { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Indigenous_ { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
    }
}
